export interface LancerUITheme {
    primaryColor: string;
    primaryHighlight: string;
    primaryShadow: string;
    lightText: string;
    darkText: string;
    backgroundColor: string;
    secondaryColor: string;
    secondaryHighlight: string;
    secondaryText: string;
    darkGrayColor: string;
    lightGrayColor: string;
    tooltipBackground: string;
    tooltipText: string;
    systemColor: string;
    weaponColor: string;
    traitColor: string;
    bonusColor: string;
    bonusListColor: string;
    techColor: string;
    talentColor: string;
    pilotStatColor: string;
    reactionColor: string;
    protocolColor: string;
    quickColor: string;
    quickTechColor: string;
    invadeColor: string;
    fullColor: string;
    fullTechColor: string;
    freeColor: string;
    moveColor: string;
    critColor: string;
    hitColor: string;
    missColor: string;
    errorColor: string;
    accuracyColor: string;
    difficultyColor: string;
    darkenColor: string;
}
export declare const themeGMS: LancerUITheme;
export declare const themeGMSDark: LancerUITheme;
export declare const themeMSMC: LancerUITheme;
export declare const themeHORUS: LancerUITheme;
export declare const themeHA: LancerUITheme;
export declare const themeSSC: LancerUITheme;
export declare const themeIPSN: LancerUITheme;
export declare const themeGAL: LancerUITheme;
export declare function applyTheme(theme: "gms" | "gmsDark" | "msmc" | "horus" | "ha" | "ssc" | "ipsn" | "gal"): void;
