// Map to: systems/lancer/assets/icons/white
import { ActionData } from "foundryvtt-lancer/models/bits/action.js";

const lancer_imgs_root = "systems/lancer/assets/icons/white/";
const la_imgs_root = "modules/lancer-automations/icons/";
const lancer_imgs = {
  accuracy: `${lancer_imgs_root}accuracy.svg`,
  campaign: `${lancer_imgs_root}campaign.svg`,
  cover_hard: `${lancer_imgs_root}cover_hard.svg`,
  downtime: `${lancer_imgs_root}downtime.svg`,
  marker: `${lancer_imgs_root}marker.svg`,
  npc_tier_custom: `${lancer_imgs_root}npc_tier_custom.svg`,
  reserve_mech: `${lancer_imgs_root}reserve_mech.svg`,
  role_tank: `${lancer_imgs_root}role_tank.svg`,
  status_dangerzone: `${lancer_imgs_root}status_dangerzone.svg`,
  tag: `${lancer_imgs_root}tag.svg`,
  activate: `${lancer_imgs_root}activate.svg`,
  compendium: `${lancer_imgs_root}compendium.svg`,
  cover_soft: `${lancer_imgs_root}cover_soft.svg`,
  drone: `${lancer_imgs_root}drone.svg`,
  mech: `${lancer_imgs_root}mech.svg`,
  orbital: `${lancer_imgs_root}orbital.svg`,
  reserve_tac: `${lancer_imgs_root}reserve_tac.svg`,
  save: `${lancer_imgs_root}save.svg`,
  status_downandout: `${lancer_imgs_root}status_downandout.svg`,
  talent: `${lancer_imgs_root}talent.svg`,
  activation_full: `${lancer_imgs_root}activation_full.svg`,
  condition_immobilized: `${lancer_imgs_root}condition_immobilized.svg`,
  d20: `${lancer_imgs_root}d20-framed.svg`,
  eclipse: `${lancer_imgs_root}eclipse.svg`,
  mech_system: `${lancer_imgs_root}mech_system.svg`,
  orbit: `${lancer_imgs_root}orbit.svg`,
  resistance_burn: `${lancer_imgs_root}resistance_burn.svg`,
  sensor: `${lancer_imgs_root}sensor.svg`,
  status_engaged: `${lancer_imgs_root}status_engaged.svg`,
  tech_full: `${lancer_imgs_root}tech_full.svg`,
  activation_quick: `${lancer_imgs_root}activation_quick.svg`,
  condition_impaired: `${lancer_imgs_root}condition_impaired.svg`,
  damage_burn: `${lancer_imgs_root}damage_burn.svg`,
  edef: `${lancer_imgs_root}edef.svg`,
  mech_weapon: `${lancer_imgs_root}mech_weapon.svg`,
  overcharge: `${lancer_imgs_root}overcharge.svg`,
  resistance_energy: `${lancer_imgs_root}resistance_energy.svg`,
  shield_outline: `${lancer_imgs_root}shield_outline.svg`,
  status_exposed: `${lancer_imgs_root}status_exposed.svg`,
  tech_quick: `${lancer_imgs_root}tech_quick.svg`,
  ammo: `${lancer_imgs_root}ammo.svg`,
  condition_jammed: `${lancer_imgs_root}condition_jammed.svg`,
  damage_energy: `${lancer_imgs_root}damage_energy.svg`,
  encounter: `${lancer_imgs_root}encounter.svg`,
  melee: `${lancer_imgs_root}melee.svg`,
  pilot: `${lancer_imgs_root}pilot.svg`,
  resistance_explosive: `${lancer_imgs_root}resistance_explosive.svg`,
  ship: `${lancer_imgs_root}ship.svg`,
  status_hidden: `${lancer_imgs_root}status_hidden.svg`,
  threat: `${lancer_imgs_root}threat.svg`,
  aoe_blast: `${lancer_imgs_root}aoe_blast.svg`,
  condition_lockon: `${lancer_imgs_root}condition_lockon.svg`,
  damage_explosive: `${lancer_imgs_root}damage_explosive.svg`,
  evasion: `${lancer_imgs_root}evasion.svg`,
  mine: `${lancer_imgs_root}mine.svg`,
  protocol: `${lancer_imgs_root}protocol.svg`,
  resistance_heat: `${lancer_imgs_root}resistance_heat.svg`,
  size_1: `${lancer_imgs_root}size_1.svg`,
  status_intangible: `${lancer_imgs_root}status_intangible.svg`,
  thrown: `${lancer_imgs_root}thrown.svg`,
  aoe_burst: `${lancer_imgs_root}aoe_burst.svg`,
  condition_shredded: `${lancer_imgs_root}condition_shredded.svg`,
  damage_heat: `${lancer_imgs_root}damage_heat.svg`,
  frame: `${lancer_imgs_root}frame.svg`,
  nested_hexagons: `${lancer_imgs_root}nested_hexagons.svg`,
  range: `${lancer_imgs_root}range.svg`,
  resistance_kinetic: `${lancer_imgs_root}resistance_kinetic.svg`,
  size_2: `${lancer_imgs_root}size_2.svg`,
  status_invisible: `${lancer_imgs_root}status_invisible.svg`,
  trait: `${lancer_imgs_root}trait.svg`,
  aoe_cone: `${lancer_imgs_root}aoe_cone.svg`,
  condition_slow: `${lancer_imgs_root}condition_slow.svg`,
  damage_kinetic: `${lancer_imgs_root}damage_kinetic.svg`,
  free_action: `${lancer_imgs_root}free_action.svg`,
  npc_class: `${lancer_imgs_root}npc_class.svg`,
  rank_1: `${lancer_imgs_root}rank_1.svg`,
  reticule: `${lancer_imgs_root}reticule.svg`,
  size_3: `${lancer_imgs_root}size_3.svg`,
  status_prone: `${lancer_imgs_root}status_prone.svg`,
  aoe_line: `${lancer_imgs_root}aoe_line.svg`,
  condition_stunned: `${lancer_imgs_root}condition_stunned.svg`,
  damage_variable: `${lancer_imgs_root}damage_variable.svg`,
  generic_item: `${lancer_imgs_root}generic_item.svg`,
  npc_feature: `${lancer_imgs_root}npc_feature.svg`,
  rank_2: `${lancer_imgs_root}rank_2.svg`,
  role_artillery: `${lancer_imgs_root}role_artillery.svg`,
  size_4: `${lancer_imgs_root}size_4.svg`,
  status_shutdown: `${lancer_imgs_root}status_shutdown.svg`,
  balance: `${lancer_imgs_root}balance.svg`,
  content_manager: `${lancer_imgs_root}content_manager.svg`,
  deactivate: `${lancer_imgs_root}deactivate.svg`,
  grenade: `${lancer_imgs_root}grenade.svg`,
  npc_template: `${lancer_imgs_root}npc_template.svg`,
  rank_3: `${lancer_imgs_root}rank_3.svg`,
  role_controller: `${lancer_imgs_root}role_controller.svg`,
  size_half: `${lancer_imgs_root}size_half.svg`,
  structure: `${lancer_imgs_root}structure.svg`,
  barrage: `${lancer_imgs_root}barrage.svg`,
  core_bonus: `${lancer_imgs_root}core_bonus.svg`,
  deployable: `${lancer_imgs_root}deployable.svg`,
  large_beam: `${lancer_imgs_root}large_beam.svg`,
  npc_tier_1: `${lancer_imgs_root}npc_tier_1.svg`,
  reaction: `${lancer_imgs_root}reaction.svg`,
  role_defender: `${lancer_imgs_root}role_defender.svg`,
  skill: `${lancer_imgs_root}skill.svg`,
  sword_array: `${lancer_imgs_root}sword_array.svg`,
  bond: `${lancer_imgs_root}bond.svg`,
  corebonus: `${lancer_imgs_root}corebonus.svg`,
  difficulty: `${lancer_imgs_root}difficulty.svg`,
  license: `${lancer_imgs_root}license.svg`,
  npc_tier_2: `${lancer_imgs_root}npc_tier_2.svg`,
  reactor: `${lancer_imgs_root}reactor.svg`,
  role_striker: `${lancer_imgs_root}role_striker.svg`,
  spikes: `${lancer_imgs_root}spikes.svg`,
  system_point: `${lancer_imgs_root}system_point.svg`,
  burning: `${lancer_imgs_root}burning.svg`,
  corepower: `${lancer_imgs_root}corepower.svg`,
  manufacturer: `${lancer_imgs_root}manufacturer.svg`,
  npc_tier_3: `${lancer_imgs_root}npc_tier_3.svg`,
  repair: `${lancer_imgs_root}repair.svg`,
  role_support: `${lancer_imgs_root}role_support.svg`,
  squad: `${lancer_imgs_root}squad.svg`,
  system: `${lancer_imgs_root}system.svg`,
};

const la_imgs = {
  "ammo-box": `${la_imgs_root}ammo-box.svg`,
  "angel-outfit": `${la_imgs_root}angel-outfit.svg`,
  "anticlockwise-rotation": `${la_imgs_root}anticlockwise-rotation.svg`,
  "auto-repair": `${la_imgs_root}auto-repair.svg`,
  "backward-time": `${la_imgs_root}backward-time.svg`,
  barrage: `${la_imgs_root}barrage.svg`,
  blinded: `${la_imgs_root}blinded.svg`,
  boot: `${la_imgs_root}boot.svg`,
  brace: `${la_imgs_root}brace.svg`,
  choice: `${la_imgs_root}choice.svg`,
  click: `${la_imgs_root}click.svg`,
  contract: `${la_imgs_root}contract.svg`,
  "cpu-shot": `${la_imgs_root}cpu-shot.svg`,
  dazed: `${la_imgs_root}dazed.svg`,
  destroyed: `${la_imgs_root}destroyed.svg`,
  disengage: `${la_imgs_root}disengage.svg`,
  dismount: `${la_imgs_root}dismount.svg`,
  falling: `${la_imgs_root}falling.svg`,
  "fast-backward-button": `${la_imgs_root}fast-backward-button.svg`,
  footprint: `${la_imgs_root}footprint.svg`,
  gears: `${la_imgs_root}gears.svg`,
  grappled: `${la_imgs_root}grappled.svg`,
  grappling: `${la_imgs_root}grappling.svg`,
  "hand-truck": `${la_imgs_root}hand-truck.svg`,
  "health-capsule": `${la_imgs_root}health-capsule.svg`,
  "health-normal": `${la_imgs_root}health-normal.svg`,
  "heavy-bullets": `${la_imgs_root}heavy-bullets.svg`,
  hover: `${la_imgs_root}hover.svg`,
  immovable: `${la_imgs_root}immovable.svg`,
  immunity: `${la_imgs_root}immunity.svg`,
  infection: `${la_imgs_root}infection.svg`,
  lagging: `${la_imgs_root}lagging.svg`,
  "light-bulb": `${la_imgs_root}light-bulb.svg`,
  "machine-gun-magazine": `${la_imgs_root}machine-gun-magazine.svg`,
  "measure-tape": `${la_imgs_root}measure-tape.svg`,
  "medical-pack": `${la_imgs_root}medical-pack.svg`,
  menu: `${la_imgs_root}menu.svg`,
  "metal-boot": `${la_imgs_root}metal-boot.svg`,
  mia_lg: `${la_imgs_root}mia_lg.svg`,
  "mountain-climbing": `${la_imgs_root}mountain-climbing.svg`,
  "mushroom-cloud": `${la_imgs_root}mushroom-cloud.svg`,
  "nested-hexagons": `${la_imgs_root}nested-hexagons.svg`,
  parachute: `${la_imgs_root}parachute.svg`,
  "path-distance": `${la_imgs_root}path-distance.svg`,
  "pause-button": `${la_imgs_root}pause-button.svg`,
  "perspective-dice-two": `${la_imgs_root}perspective-dice-two.svg`,
  pickup: `${la_imgs_root}pickup.svg`,
  pin: `${la_imgs_root}pin.svg`,
  push: `${la_imgs_root}push.svg`,
  "radar-sweep": `${la_imgs_root}radar-sweep.svg`,
  "rally-the-troops": `${la_imgs_root}rally-the-troops.svg`,
  ram: `${la_imgs_root}ram.svg`,
  reload: `${la_imgs_root}reload.svg`,
  resist_all: `${la_imgs_root}resist_all.svg`,
  rifle: `${la_imgs_root}rifle.svg`,
  search: `${la_imgs_root}search.svg`,
  skirmish: `${la_imgs_root}skirmish.svg`,
  speedometer: `${la_imgs_root}speedometer.svg`,
  "stone-pile": `${la_imgs_root}stone-pile.svg`,
  suicide: `${la_imgs_root}suicide.svg`,
  teleport: `${la_imgs_root}teleport.svg`,
  throttled: `${la_imgs_root}throttled.svg`,
  throw: `${la_imgs_root}throw.svg`,
  "time-bomb": `${la_imgs_root}time-bomb.svg`,
  tombstone: `${la_imgs_root}tombstone.svg`,
  "trash-can": `${la_imgs_root}trash-can.svg`,
  underhand: `${la_imgs_root}underhand.svg`,
  "up-card": `${la_imgs_root}up-card.svg`,
  vote: `${la_imgs_root}vote.svg`,
};

export function getActivationIcon(action: ActionData) {
  if (/grenade/i.test(action?.name ?? "")) return "systems/lancer/assets/icons/white/grenade.svg";
  const isTech = action?.tech_attack === true;
  const activation = action?.activation || "";
  const activationLower = activation.toLowerCase();
  if (isTech || activationLower.includes("tech")) {
    if (activationLower.includes("full")) return "systems/lancer/assets/icons/tech_full.svg";
    return "systems/lancer/assets/icons/tech_quick.svg";
  }
  if (activationLower.includes("full")) return "mdi mdi-hexagon-slice-6";
  if (activationLower.includes("protocol")) return "systems/lancer/assets/icons/protocol.svg";
  if (activationLower.includes("free")) return "systems/lancer/assets/icons/free_action.svg";
  if (activationLower.includes("reaction")) return "systems/lancer/assets/icons/reaction.svg";
  if (activationLower.includes("quick")) return "mdi mdi-hexagon-slice-3";
  if (activationLower.includes("invade")) return "modules/lancer-automations/icons/cpu-shot.svg";
  return null;
}

export const imgs = {
  lancer: lancer_imgs,
  la: la_imgs,
};
